//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelpDesk.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author Rating.
        /// </summary>
        public static string AuthorRating {
            get {
                return ResourceManager.GetString("AuthorRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Buy Now.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Easy Setup.
        /// </summary>
        public static string EasySetup {
            get {
                return ResourceManager.GetString("EasySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get support.
        /// </summary>
        public static string Getsupport {
            get {
                return ResourceManager.GetString("Getsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Happy Costomers.
        /// </summary>
        public static string happycostomers {
            get {
                return ResourceManager.GetString("happycostomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We have a Support Desk for our users and a well experienced team to quickly answer your questions..
        /// </summary>
        public static string into6 {
            get {
                return ResourceManager.GetString("into6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NST-desk is a web application that enables our clients to obtain their preferred products while receiving an after-sales services.
        ///                    Because the client is our main priority at NST-desk, we offer an after-sales service in which a team of qualified agents is available to address your concerns..
        /// </summary>
        public static string intro1 {
            get {
                return ResourceManager.GetString("intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We love our work and it shows. A motivated young team formed mainly by computer engineers,
        ///                    we know this environment like the back of our hand.
        ///                    We are ready to take on any challenge and we are 100% involved in all the projects we undertake..
        /// </summary>
        public static string intro2 {
            get {
                return ResourceManager.GetString("intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We make our products easy to setup and customize..
        /// </summary>
        public static string intro3 {
            get {
                return ResourceManager.GetString("intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We improve our products after release and you will get it for free..
        /// </summary>
        public static string intro4 {
            get {
                return ResourceManager.GetString("intro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We provide fast and professional support through support system..
        /// </summary>
        public static string intro5 {
            get {
                return ResourceManager.GetString("intro5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LatestProducts.
        /// </summary>
        public static string LatestProducts {
            get {
                return ResourceManager.GetString("LatestProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lifetime Updates.
        /// </summary>
        public static string LifetimeUpdates {
            get {
                return ResourceManager.GetString("LifetimeUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Live Demo.
        /// </summary>
        public static string LiveDemo {
            get {
                return ResourceManager.GetString("LiveDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NST-Desk.
        /// </summary>
        public static string NST_Desk {
            get {
                return ResourceManager.GetString("NST-Desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outstanding Support.
        /// </summary>
        public static string OutstandingSupport {
            get {
                return ResourceManager.GetString("OutstandingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View Products.
        /// </summary>
        public static string ViewProducts {
            get {
                return ResourceManager.GetString("ViewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visit our Support Desk.
        /// </summary>
        public static string VisitourSupportDesk {
            get {
                return ResourceManager.GetString("VisitourSupportDesk", resourceCulture);
            }
        }
    }
}
